# Generated by Django 3.0.4 on 2020-03-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=200)),
                ('description_categorie', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_participant', models.CharField(max_length=200)),
                ('prenom_participant', models.CharField(max_length=200)),
                ('courriel_participant', models.EmailField(max_length=300)),
                ('date_naissance', models.DateTimeField()),
                ('actif', models.BooleanField(verbose_name='est présentement actif')),
                ('categories', models.ManyToManyField(to='particpants.Categorie')),
            ],
        ),
    ]
