# Generated by Django 3.0.4 on 2020-03-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particpants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_participant', models.CharField(max_length=200)),
                ('prenom_participant', models.CharField(max_length=200)),
                ('courriel_participant', models.EmailField(max_length=300)),
                ('date_naissance', models.DateTimeField()),
                ('actif', models.BooleanField(verbose_name='est présentement actif')),
            ],
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.AddField(
            model_name='categorie',
            name='participants',
            field=models.ManyToManyField(to='particpants.Participant'),
        ),
    ]
