# Generated by Django 3.0.4 on 2020-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particpants', '0003_auto_20200310_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='participants',
        ),
        migrations.AddField(
            model_name='participant',
            name='categories',
            field=models.ManyToManyField(to='particpants.Categorie'),
        ),
    ]
