# Generated by Django 3.0.4 on 2020-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particpants', '0004_auto_20200311_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='est présentement actif'),
        ),
    ]
